import fs from "node:fs";
import { geoMercator, geoPath } from "d3-geo";

const raw = JSON.parse(fs.readFileSync("/tmp/us-counties.json", "utf8"));

const META = {
  "17197": "Will",
  "17031": "Cook",
  "17043": "DuPage",
  "17089": "Kane",
  "17093": "Kendall",
  "17097": "Lake",        // IL
  "17111": "McHenry",
  "17063": "Grundy",
  "17037": "DeKalb",
  "55059": "Kenosha",     // WI
  "18089": "Lake (IN)",   // Indiana
  "18127": "Porter",
};

const wanted = new Set(Object.keys(META));
const feats = raw.features.filter((f) => wanted.has(f.id));
console.error("matched", feats.length, "of", wanted.size);

const fc = { type: "FeatureCollection", features: feats };

const W = 900, H = 780, PAD = 28;
const proj = geoMercator().fitExtent(
  [[PAD, PAD], [W - PAD, H - PAD]],
  fc,
);
const path = geoPath(proj);

const out = feats.map((f) => {
  const c = path.centroid(f);
  return {
    fips: f.id,
    name: META[f.id],
    d: path(f),
    cx: +c[0].toFixed(1),
    cy: +c[1].toFixed(1),
  };
});

const body = `// AUTO-GENERATED by scripts/gen-geo.mjs — real Chicago-metro county shapes.
export const GEO_W = ${W};
export const GEO_H = ${H};
export type CountyShape = { fips: string; name: string; d: string; cx: number; cy: number };
export const COUNTY_SHAPES: CountyShape[] = ${JSON.stringify(out)};
`;
fs.writeFileSync("lib/chicago-geo.ts", body);
console.error("wrote lib/chicago-geo.ts", (body.length / 1024).toFixed(1), "kb");
